# Generated by Django 2.2 on 2019-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ('id',), 'verbose_name': 'Linea', 'verbose_name_plural': 'Lineas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id',), 'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
    ]
