# Generated by Django 2.2 on 2019-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190416_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='icono',
            field=models.CharField(max_length=20, verbose_name='icono'),
        ),
    ]
